//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2015-12-14 14:10:23 by Zhaoqiang
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
//using System.ComponentModel.DataAnnotations;


namespace Weigou.Model
{    
    public class CarDataInfo
    {
         
    }
}
